# Generated by Django 4.2.6 on 2023-11-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'Pozwala wyświetlić obiekty modelu osoba.')]},
        ),
    ]
