# Generated by Django 4.2.6 on 2023-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_osoba_miesiac_dodania_alter_stanowisko_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_dodania',
            field=models.DateField(default=11),
        ),
    ]
