# Generated by Django 4.2.6 on 2023-10-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta'), (3, 'Inna')], max_length=1),
        ),
    ]
