# Generated by Django 4.2.6 on 2023-11-06 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_osoba_plec'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='miesiac_dodania',
            field=models.DateField(default=datetime.date(2023, 11, 1)),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='opis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
