# Generated by Django 4.2.6 on 2023-10-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta'), (3, 'Inna')]),
        ),
    ]
